-- Inserir súmulas STJ 1-50
INSERT INTO public."SUMULAS STJ" (id, "Título da Súmula", "Texto da Súmula", "Data de Aprovação") VALUES
(1, 'Súmula 1', 'O foro do domicílio ou da residência do alimentando é o competente para a ação de investigação de paternidade, quando cumulada com a de alimentos.', '08/05/1990'),
(2, 'Súmula 2', 'Não cabe o habeas corpus contra decisão condenatória a pena de multa, ou relativo a processo em curso por infração penal a que a pena pecuniária seja a única cominada.', '08/05/1990'),
(3, 'Súmula 3', 'Compete ao Tribunal Regional Federal dirimir conflito de competência verificado, na respectiva região, entre Juiz Federal e Juiz Estadual investido de jurisdição federal.', '08/05/1990'),
(4, 'Súmula 4', 'Compete ao Tribunal Regional Federal dirimir conflito de competência ocorrido, na respectiva região, entre Juiz de Estado e Juiz Federal.', '08/05/1990'),
(5, 'Súmula 5', 'A competência por delegação só se prorroga se incompetente, em razão da matéria ou da hierarquia, o Juízo deprecado.', '08/05/1990'),
(6, 'Súmula 6', 'Compete à Justiça Comum Estadual processar e julgar delito decorrente de acidente de trânsito envolvendo viatura de Polícia Militar, salvo se autor e vítima forem policiais militares em situação de atividade.', '29/05/1990'),
(7, 'Súmula 7', 'A pretensão de simples reexame de prova não enseja recurso especial.', '29/05/1990'),
(8, 'Súmula 8', 'A medida cautelar pode ser revogada ou modificada a qualquer tempo, mas a que impõe a indisponibilidade de bens não pode ser decretada sem a oitiva da parte contrária, salvo quando essa providência importar em ineficácia da medida.', '15/06/1990'),
(9, 'Súmula 9', 'A exigência da prisão provisória, para apelar, não ofende a garantia constitucional da presunção de inocência.', '17/08/1990'),
(10, 'Súmula 10', 'A indenização por dano moral não está sujeita à restrição limitativa prevista na Lei de Imprensa.', '17/08/1990'),
(11, 'Súmula 11', 'A prescrição de crédito trabalhista só se interrompe pelo ajuizamento de reclamação perante a Justiça do Trabalho.', '17/08/1990'),
(12, 'Súmula 12', 'Em desapropriação, são cumuláveis juros compensatórios e moratórios.', '17/08/1990'),
(13, 'Súmula 13', 'A divergência entre julgados do mesmo tribunal não enseja recurso especial.', '12/09/1990'),
(14, 'Súmula 14', 'Habeas corpus não constitui substitutivo de recurso ordinário ou de apelação.', '26/09/1990'),
(15, 'Súmula 15', 'Compete à Justiça Estadual processar e julgar os litígios decorrentes de acidente do trabalho.', '26/09/1990'),
(16, 'Súmula 16', 'Compete à Justiça Estadual processar e julgar, em ambas as instâncias, as causas de acidente do trabalho, ainda que promovidas contra a União, suas autarquias, empresas públicas ou sociedades de economia mista.', '10/10/1990'),
(17, 'Súmula 17', 'Quando o falso se exaure no estelionato, sem mais potencialidade lesiva, é por este absorvido.', '10/10/1990'),
(18, 'Súmula 18', 'A sentença concessiva do benefício da assistência judiciária é irrecorrível.', '10/10/1990'),
(19, 'Súmula 19', 'A fixação do valor da indenização ou de seu montante, no Juízo cível, não prevalece na esfera penal.', '10/10/1990'),
(20, 'Súmula 20', 'A mercadoria importada de país signatário do GATT é isenta do ICM, quando contemplado com esse favor o similar nacional.', '24/10/1990'),
(21, 'Súmula 21', 'Dívida de jogo, por não encontrar amparo na lei, não gera obrigação de pagar, mas faculta a restituição voluntária do pagamento, salvo quando mediante fraude o ganho for devido.', '24/10/1990'),
(22, 'Súmula 22', 'A Justiça do Trabalho é competente para julgar as ações de indenização por dano moral e material decorrentes da relação de trabalho.', '24/10/1990'),
(23, 'Súmula 23', 'Contrato de abertura de crédito em conta-corrente, acompanhado do demonstrativo de débito, constitui documento hábil para o ajuizamento da ação monitória.', '24/10/1990'),
(24, 'Súmula 24', 'A reincidência penal não pode ser considerada como circunstância agravante e, simultaneamente, como circunstância judicial.', '07/11/1990'),
(25, 'Súmula 25', 'A Câmara Criminal do Tribunal de Justiça não tem competência para julgar recurso de habeas corpus, quando interposto contra decisão condenatória em crime doloso contra a vida.', '07/11/1990'),
(26, 'Súmula 26', 'O Juiz Criminal tem competência para o julgamento de crime doloso contra a vida, quando cometido em situação de flagrante, ainda que o réu seja policial militar.', '21/11/1990'),
(27, 'Súmula 27', 'Compete ao Juízo do local do ato ou fato que deu origem à execução fiscal decidir sobre ela.', '05/12/1990'),
(28, 'Súmula 28', 'O devedor de alimentos oferece, na execução, bens à penhora ou requerer o parcelamento do débito, caso em que se converterá a prisão civil em civil.', '05/12/1990'),
(29, 'Súmula 29', 'Proposta a execução fiscal, a posterior mudança de domicílio do executado não desloca a competência já fixada.', '05/12/1990'),
(30, 'Súmula 30', 'A comissão permanente de licitação tem legitimidade para representar a entidade licitadora nos processos judiciais relativos ao certame que promoveu.', '12/12/1990'),
(31, 'Súmula 31', 'É legítima a incidência do Imposto sobre Serviços de Qualquer Natureza (ISS) sobre operações de arrendamento mercantil (leasing).', '19/12/1990'),
(32, 'Súmula 32', 'O Banco Central não tem legitimidade para figurar no polo passivo de ação de repetição de indébito referente a expurgos inflacionários dos planos econômicos, ainda que decorrente de contas vinculadas ao FGTS.', '19/12/1990'),
(33, 'Súmula 33', 'A multa moratória prevista no art. 52, § 1º, da Lei n. 8.212/1991, não se aplica às contribuições previdenciárias arrecadadas pelo FGTS.', '26/02/1992'),
(34, 'Súmula 34', 'A indenização por dano moral não está sujeita à tarifação estabelecida pela Lei de Imprensa.', '04/03/1992'),
(35, 'Súmula 35', 'Incide correção monetária sobre as prestações pagas, quando se trate de complemento de pensão.', '04/03/1992'),
(36, 'Súmula 36', 'A correção monetária integra o valor da causa.', '11/03/1992'),
(37, 'Súmula 37', 'São cumuláveis as indenizações por dano material e dano moral oriundos do mesmo fato.', '11/03/1992'),
(38, 'Súmula 38', 'Compete à Justiça Estadual Comum, na vigência da Constituição de 1988, o processo por contravenção penal, ainda que praticada em detrimento de bens, serviços ou interesse da União ou de suas entidades.', '18/03/1992'),
(39, 'Súmula 39', 'Prescreve em vinte anos a ação para haver indenização, por responsabilidade civil, de sociedade de economia mista.', '18/03/1992'),
(40, 'Súmula 40', 'Para obtenção dos benefícios de litigante de má-fé, é indispensável que a parte vencedora tenha sofrido prejuízo.', '25/03/1992'),
(41, 'Súmula 41', 'O Tribunal de Alçada não é competente para julgar recurso de decisão judicial que recebeu ou rejeitou denúncia ou queixa.', '08/04/1992'),
(42, 'Súmula 42', 'Compete à Justiça Comum Estadual processar e julgar as causas cíveis em que é parte sociedade de economia mista e os crimes praticados em seu detrimento.', '15/04/1992'),
(43, 'Súmula 43', 'Incide correção monetária sobre dívida por ato ilícito a partir da data do efetivo prejuízo.', '22/04/1992'),
(44, 'Súmula 44', 'A sobrevinda da maioridade penal não interfere na apuração do ato infracional nem na aplicabilidade de medida socioeducativa em curso, inclusive na liberdade assistida, enquanto não atingida a idade de 21 anos.', '29/04/1992'),
(45, 'Súmula 45', 'No reexame necessário, é defeso, ao Tribunal, agravar a condenação imposta à Fazenda Pública.', '06/05/1992'),
(46, 'Súmula 46', 'A segunda fase do procedimento do júri, quando julgado procedente o recurso de apelação, é de competência da Vara do Júri que proferiu a primeira sentença.', '13/05/1992'),
(47, 'Súmula 47', 'Reajustada a aposentadoria de ex-celetista pelo mesmo índice de revisão dos benefícios dos servidores públicos, a suplementação, se devida, será a diferença entre os dois valores.', '20/05/1992'),
(48, 'Súmula 48', 'Compete ao Juízo do local da obtenção da prova antecipatória apreciá-la e decretá-la.', '27/05/1992'),
(49, 'Súmula 49', 'O prazo de prescrição da ação de servidor público, contra a Fazenda Pública, é de cinco anos.', '10/06/1992'),
(50, 'Súmula 50', 'Compete à Justiça Federal decidir sobre a existência de interesse jurídico que justifique a presença, no processo, da União, suas autarquias ou empresas públicas.', '17/06/1992')