-- Criar tabela CPPM com estrutura idêntica ao Código Penal
CREATE TABLE "CPPM – Código de Processo Penal Militar" (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "Artigo" text,
  "Número do Artigo" text,
  "Narração" text,
  "Comentario" text,
  "Aula" text,
  explicacao_tecnico text,
  explicacao_resumido text,
  explicacao_simples_menor16 text,
  explicacao_simples_maior16 text,
  exemplo text,
  versao_conteudo integer DEFAULT 1,
  termos jsonb,
  flashcards jsonb,
  questoes jsonb,
  ultima_atualizacao timestamp without time zone,
  termos_aprofundados jsonb DEFAULT '{}'::jsonb,
  visualizacoes integer DEFAULT 0,
  ultima_visualizacao timestamp with time zone
);

-- Habilitar RLS
ALTER TABLE "CPPM – Código de Processo Penal Militar" ENABLE ROW LEVEL SECURITY;

-- Policy para leitura pública
CREATE POLICY "CPPM é público para leitura"
  ON "CPPM – Código de Processo Penal Militar"
  FOR SELECT
  USING (true);

-- Policy para atualização pelo sistema
CREATE POLICY "Sistema pode atualizar CPPM"
  ON "CPPM – Código de Processo Penal Militar"
  FOR UPDATE
  USING (true);

-- Transferir todos os dados da TABELA PARA EDITAR (756 registros)
INSERT INTO "CPPM – Código de Processo Penal Militar" ("Artigo", "Número do Artigo")
SELECT 
  "Artigo",
  "Número do Artigo"
FROM "TABELA PARA EDITAR"
ORDER BY id;

-- Validação
DO $$
DECLARE
  total_records integer;
  total_artigos integer;
BEGIN
  SELECT COUNT(*) INTO total_records FROM "CPPM – Código de Processo Penal Militar";
  SELECT COUNT(*) INTO total_artigos FROM "CPPM – Código de Processo Penal Militar" WHERE "Número do Artigo" IS NOT NULL;
  
  RAISE NOTICE '✅ Tabela CPPM criada com sucesso!';
  RAISE NOTICE '📊 Total de registros: %', total_records;
  RAISE NOTICE '📄 Artigos numerados: %', total_artigos;
  RAISE NOTICE '🏛️ Estruturas (títulos/cabeçalhos): %', total_records - total_artigos;
END $$;