-- Inserir súmulas STJ 51-100
INSERT INTO public."SUMULAS STJ" (id, "Título da Súmula", "Texto da Súmula", "Data de Aprovação") VALUES
(51, 'Súmula 51', 'A norma legal que altera o prazo de recolhimento da obrigação tributária não se sujeita ao princípio da anterioridade.', '24/06/1992'),
(52, 'Súmula 52', 'Encerrada a instrução criminal, fica superada a alegação de constrangimento por excesso de prazo.', '01/07/1992'),
(53, 'Súmula 53', 'Não cabe agravo regimental contra decisão proferida pelo relator que, em pedido ou recurso, autoriza a realização de citação, penhora ou qualquer outra diligência.', '01/07/1992'),
(54, 'Súmula 54', 'Os juros moratórios fluem a partir do evento danoso, em caso de responsabilidade extracontratual.', '15/07/1992'),
(55, 'Súmula 55', 'Não cabe agravo de instrumento contra decisão de relator que, em agravo regimental, decide pela manutenção de decisão de admissibilidade de recurso especial.', '22/07/1992'),
(56, 'Súmula 56', 'A liquidação por forma diversa da estabelecida na sentença não ofende a coisa julgada.', '05/08/1992'),
(57, 'Súmula 57', 'Demonstrada a impossibilidade de localização dos bens penhorados, o juiz poderá, de ofício, determinar a indisponibilidade de outros bens da parte executada, nos limites da execução.', '19/08/1992'),
(58, 'Súmula 58', 'Proposta a execução fiscal, a posterior mudança de domicílio do executado não desloca a competência já fixada.', '26/08/1992'),
(59, 'Súmula 59', 'Não existe direito adquirido a regime jurídico-funcional de servidor público.', '09/09/1992'),
(60, 'Súmula 60', 'É nula a obrigação cambial assumida por procurador do mutuário vinculado ao mutuante, no exclusivo interesse deste.', '16/09/1992'),
(61, 'Súmula 61', 'O Seguro de Acidente do Trabalho não exclui a responsabilidade civil da empresa.', '23/09/1992'),
(62, 'Súmula 62', 'A indenização por dano moral não está sujeita à restrição limitativa prevista no Código Brasileiro de Aeronáutica.', '30/09/1992'),
(63, 'Súmula 63', 'São inconstitucionais o inciso II e a alínea "a" do inciso III do art. 3º do Decreto-lei n. 911/69, e o art. 1º do Decreto-lei n. 1.514/76, que institui a prisão civil do alienante fiduciário.', '21/10/1992'),
(64, 'Súmula 64', 'Não constitui crime a conduta do Juiz, membro do Ministério Público, advogado ou de servidor público, que desacata juiz do processo em que atua.', '28/10/1992'),
(65, 'Súmula 65', 'Compete ao Tribunal Regional Federal dirimir conflito de competência entre Juiz de Direito e Juiz Federal, na respectiva região.', '04/11/1992'),
(66, 'Súmula 66', 'Compete à Justiça Federal processar e julgar execução fiscal promovida por conselho de fiscalização profissional.', '11/11/1992'),
(67, 'Súmula 67', 'Na execução fiscal, verificados os pressupostos do art. 4º da Lei 6.830/80, é cabível o arresto dos bens do executado.', '18/11/1992'),
(68, 'Súmula 68', 'A parcela relativa ao ICMS inclui-se na base de cálculo do PIS.', '25/11/1992'),
(69, 'Súmula 69', 'Na definição do valor da pensão por morte, não prevalece a lei em vigor na data do óbito se a incapacidade, à época, era apenas parcial.', '02/12/1992'),
(70, 'Súmula 70', 'É inadmissível a interdição de estabelecimento como meio coercitivo para cobrança de tributo.', '09/12/1992'),
(71, 'Súmula 71', 'O bacalhau importado de país signatário do GATT é isento do ICM.', '16/12/1992'),
(72, 'Súmula 72', 'A comprovação da mora é imprescindível à busca e apreensão do bem alienado fiduciariamente.', '10/03/1993'),
(73, 'Súmula 73', 'A utilização de papel termossensível em fac-símile não invalida comunicação de atos processuais, desde que seja garantida a sua legibilidade.', '17/03/1993'),
(74, 'Súmula 74', 'Para efeitos penais, o reconhecimento da menoridade do réu requer prova por documento hábil.', '24/03/1993'),
(75, 'Súmula 75', 'Compete à Justiça Comum Estadual processar e julgar o policial militar por crime de promover ou facilitar a fuga de preso de estabelecimento penal.', '31/03/1993'),
(76, 'Súmula 76', 'A falta de registro de contrato social no órgão competente não obsta a propositura de ação ou sua defesa.', '14/04/1993'),
(77, 'Súmula 77', 'A Caixa Econômica Federal é parte ilegítima para figurar no polo passivo das ações relativas às contribuições para o FGTS.', '21/04/1993'),
(78, 'Súmula 78', 'Compete ao Juízo do local da obtenção da prova antecipatória apreciá-la e decretá-la.', '28/04/1993'),
(79, 'Súmula 79', 'Nas ações de indenização por ato ilícito, a fluência dos juros moratórios se dá a partir da data do evento danoso.', '05/05/1993'),
(80, 'Súmula 80', 'A cobrança de juros capitalizados, no mútuo bancário, é permitida quando houver expressa pactuação.', '12/05/1993'),
(81, 'Súmula 81', 'Não se concede habeas corpus quando já extinta a pena privativa de liberdade.', '19/05/1993'),
(82, 'Súmula 82', 'São inconstitucionais o art. 12, alínea "a", da Lei n. 8.024/90 e os arts. 6º, 7º e 8º da Lei n. 8.088/90.', '26/05/1993'),
(83, 'Súmula 83', 'Não se conhece do recurso especial pela divergência, quando a orientação do Tribunal se firmou no mesmo sentido da decisão recorrida.', '09/06/1993'),
(84, 'Súmula 84', 'É admissível a oposição de embargos de declaração ao acórdão publicado, ainda que em separata.', '16/06/1993'),
(85, 'Súmula 85', 'Nas relações jurídicas de trato sucessivo em que a Fazenda Pública figure como devedora, quando não tiver sido negado o próprio direito reclamado, a prescrição atinge apenas as prestações vencidas antes do quinquênio anterior à propositura da ação.', '23/06/1993'),
(86, 'Súmula 86', 'Cabe recurso especial contra acórdão proferido no julgamento de agravo de instrumento.', '30/06/1993'),
(87, 'Súmula 87', 'Quando a nota promissória não contiver a época do pagamento, será considerada como à vista (Súmula n. 258 do TFR).', '07/07/1993'),
(88, 'Súmula 88', 'A indenização por dano moral não está sujeita a restrições legislativas.', '04/08/1993'),
(89, 'Súmula 89', 'É permitida a acumulação dos benefícios de pensão por morte e auxílio-acidente.', '11/08/1993'),
(90, 'Súmula 90', 'Compete à Justiça Estadual processar e julgar os crimes de moeda falsa, quando não houver lesão a bem, serviço ou interesse da União, de suas entidades autárquicas ou empresas públicas.', '18/08/1993'),
(91, 'Súmula 91', 'Para efeitos do art. 4º da Lei n. 6.830/80 (Lei de Execução Fiscal), a prescrição ocorrida antes da propositura da ação pode ser decretada de ofício (art. 219, § 5º, do CPC).', '25/08/1993'),
(92, 'Súmula 92', 'É inconstitucional a Lei Municipal que tenha estabelecido, antes da Emenda Constitucional 29/2000, alíquotas progressivas para o IPTU, salvo se destinada a assegurar o cumprimento da função social da propriedade urbana.', '01/09/1993'),
(93, 'Súmula 93', 'A legislação aduaneira, ao limitar a R$ 500,00 (quinhentos dólares dos Estados Unidos da América) o valor de bens que podem ser importados do exterior, por via terrestre, com a alíquota reduzida de 50% (cinquenta por cento), não é discriminatória em relação às importações por outras vias.', '08/09/1993'),
(94, 'Súmula 94', 'A parcela relativa ao ICMS inclui-se na base de cálculo do PIS incidente sobre a receita bruta das pessoas jurídicas que promovem vendas de mercadorias.', '15/09/1993'),
(95, 'Súmula 95', 'A recusa da empresa em viabilizar o seguro de vida em grupo não pode resultar em dano ao empregado.', '29/09/1993'),
(96, 'Súmula 96', 'O crime de extorsão consuma-se independentemente da obtenção da vantagem indevida.', '06/10/1993'),
(97, 'Súmula 97', 'O empregado que recebe salário complessivo deve postular pela diferença remuneratória devida em relação às horas extras.', '13/10/1993'),
(98, 'Súmula 98', 'Embargos de declaração manifestados com notório propósito de prequestionamento não têm caráter protelatório.', '20/10/1993'),
(99, 'Súmula 99', 'O Ministério Público tem legitimidade para recorrer no processo em que oficiou como fiscal da lei, ainda que não haja recurso da parte.', '27/10/1993'),
(100, 'Súmula 100', 'Cabe recurso especial contra acórdão proferido no julgamento de agravo regimental.', '03/11/1993')