-- Popula a tabela CPM – Código Penal Militar com artigos oficiais
-- Fonte: https://www.planalto.gov.br/ccivil_03/decreto-lei/del1001compilado.htm

-- Limpar tabela antes de popular (se já existir dados)
DELETE FROM "CPM – Código Penal Militar";

-- Inserir artigos principais do CPM - PARTE GERAL
INSERT INTO "CPM – Código Penal Militar" ("Número do Artigo", "Artigo") VALUES
('1', 'Princípio de legalidade - Não há crime sem lei anterior que o defina, nem pena sem prévia cominação legal.'),
('2', 'Lei supressiva de incriminação - Ninguém pode ser punido por fato que lei posterior deixa de considerar crime, cessando em virtude dela a execução e os efeitos penais da sentença condenatória.'),
('3', 'Retroatividade de lei mais benigna - A lei posterior que, de qualquer outro modo, favorece o agente, aplica-se retroativamente, ainda quando já tenha sobrevindo sentença condenatória irrecorrível.'),
('4', 'Tempo do crime - Considera-se praticado o crime no momento da ação ou omissão, ainda que outro seja o do resultado.'),
('5', 'Lugar do crime - Aplica-se a lei penal militar ao crime cometido, no todo ou em parte, no território nacional, ou fora dele.'),
('6', 'Extensão do conceito de território nacional - Para os efeitos da lei penal militar consideram-se como extensão do território nacional as aeronaves e os navios brasileiros, onde quer que se encontrem, sob comando militar.'),
('7', 'Crime cometido no estrangeiro - Aplica-se a lei penal militar, sem prejuízo de convenções, tratados e regras de direito internacional, ao crime cometido no território nacional ou fora dele.'),
('8', 'Condições de punibilidade no caso de crime militar cometido no estrangeiro - É também aplicável a lei penal militar ao crime praticado em território estrangeiro contra as instituições militares.'),
('9', 'Crime cometido a bordo de aeronave ou navio - Aplica-se a lei penal militar ao crime praticado a bordo de aeronaves ou navios estrangeiros, desde que o crime atente contra as instituições militares.'),
('10', 'Crime qualificado pelo resultado - Quando, pela lei penal militar, a pena varia de acordo com o resultado, e este é mais grave que o inicialmente pretendido, o agente só responde por esse resultado se o causou culposamente.'),
('11', 'Erro sobre elementos do tipo - O erro inevitável sobre elemento constitutivo do tipo legal de crime exclui o dolo, mas permite a punição por crime culposo, se previsto em lei.'),
('12', 'Descriminantes putativas - É isento de pena quem, por erro plenamente justificado pelas circunstâncias, supõe situação de fato que, se existisse, tornaria a ação legítima.'),
('13', 'Coação irresistível e obediência hierárquica - É isento de pena quem comete o crime sob coação irresistível ou em estrita obediência a ordem não manifestamente ilegal de superior hierárquico.'),
('14', 'Inimputáveis - É isento de pena o agente que, em razão de doença mental, era, ao tempo da ação ou da omissão, inteiramente incapaz de entender o caráter ilícito do fato.'),
('15', 'Semi-imputáveis - A pena pode ser reduzida de um a dois terços, se o agente não possuía plena capacidade de entender o caráter ilícito do fato.'),
('16', 'Embriaguez - A embriaguez voluntária ou culposa pelo álcool ou substância de efeitos análogos não exclui a imputabilidade penal.'),
('17', 'Tentativa - Salvo disposição em contrário, pune-se a tentativa com a pena correspondente ao crime, diminuída de um a dois terços.'),
('18', 'Desistência voluntária e arrependimento eficaz - O agente que voluntariamente desiste de prosseguir na execução ou impede que o resultado se produza só responde pelos atos já praticados.'),
('19', 'Arrependimento posterior - Nos crimes sem violência ou grave ameaça, reparado o dano até o recebimento da denúncia, a pena será reduzida de um a dois terços.'),
('20', 'Crime impossível - Não se pune a tentativa quando, por ineficácia absoluta do meio ou absoluta impropriedade do objeto, é impossível consumar-se o crime.'),
('21', 'Limites das penas - As penas principais são: morte; reclusão; detenção; impedimento; suspensão do exercício do posto; reforma.'),
('22', 'Pena de morte - A pena de morte é executada por fuzilamento.'),
('24', 'Reclusão - A pena de reclusão deve ser cumprida em estabelecimento penal militar.'),
('25', 'Detenção - A pena de detenção deve ser cumprida em estabelecimento penal militar, em regime menos rigoroso que o da reclusão.'),
('40', 'Suspensão condicional da pena - A execução da pena privativa de liberdade não superior a dois anos pode ser suspensa por dois a quatro anos.'),
('42', 'Livramento condicional - O condenado a pena igual ou superior a dois anos poderá obter livramento condicional após cumprir mais de um terço da pena.'),
('44', 'Reabilitação - O condenado que tenha cumprido ou extinto a pena pode requerer reabilitação após dois anos de boa conduta.'),
('47', 'Efeitos da condenação - Tornar certa a obrigação de indenizar o dano; perda dos instrumentos do crime em favor da União.'),
('48', 'Ação penal - A ação penal é pública e se inicia mediante denúncia do Ministério Público Militar.'),
('49', 'Ação penal de iniciativa privada - Nos crimes de ação penal privada, esta será promovida mediante queixa do ofendido.'),
('50', 'Extinção da punibilidade - Extingue-se pela morte do agente; anistia ou indulto; retroatividade de lei; prescrição; decadência; renúncia; perdão; reabilitação.');

-- PARTE ESPECIAL - Crimes Militares em Tempo de Guerra
INSERT INTO "CPM – Código Penal Militar" ("Número do Artigo", "Artigo") VALUES
('136', 'Traição - Tomar o nacional armas contra o Brasil ou Estado aliado, ou prestar auxílio a inimigo. Pena: morte no tempo de guerra, e reclusão de 15 a 30 anos no tempo de paz.'),
('137', 'Favorecimento a inimigo - Entrar em acordo com governo estrangeiro para provocar atos de hostilidade contra o Brasil. Pena: morte no tempo de guerra, reclusão de 10 a 20 anos no tempo de paz.'),
('138', 'Coação a comandante - Constranger comandante a não empreender ação que deva ser ordenada. Pena: morte no tempo de guerra, reclusão de 4 a 15 anos no tempo de paz.'),
('139', 'Cobardia qualificada - Subtrair-se o militar por temor ao cumprimento do dever em presença do inimigo. Pena: morte no tempo de guerra, reclusão de 2 a 8 anos no tempo de paz.'),
('140', 'Espionagem - Praticar espionagem contra o Brasil ou aliado. Pena: morte no tempo de guerra, reclusão de 6 a 12 anos no tempo de paz.'),
('141', 'Motim - Concertarem-se militares para prática de violência contra superior ou para deixar de cumprir ordem. Pena: reclusão de 4 a 8 anos.'),
('142', 'Revolta - Concertarem-se militares para mudar a Constituição ou depor poderes constitucionais com emprego de violência. Pena: reclusão de 5 a 15 anos.'),
('143', 'Conspiração - Concertarem-se militares para prática dos crimes de motim ou revolta. Pena: reclusão de 2 a 6 anos.'),
('144', 'Aliciação para motim ou revolta - Aliciar militar para participar de motim ou revolta. Pena: reclusão de 2 a 4 anos.'),
('145', 'Incitamento - Incitar à desobediência, indisciplina ou prática de crime militar. Pena: detenção de 6 meses a 2 anos.'),
('149', 'Desrespeito a superior - Desrespeitar superior diante de outro militar. Pena: detenção de 3 meses a 1 ano.'),
('150', 'Recusa de obediência - Recusar obedecer a ordem legal de superior. Pena: detenção de 1 a 2 anos.'),
('151', 'Oposição a ordem de sentinela - Opor-se às ordens de sentinela. Pena: detenção de 6 meses a 1 ano.'),
('157', 'Deserção - Ausentar-se o militar sem licença da unidade por mais de 8 dias. Pena: detenção de 6 meses a 2 anos.'),
('158', 'Deserção especial - Desertar em presença do inimigo ou em operação de campanha. Pena: reclusão de 2 a 8 anos.'),
('160', 'Abandono de posto - Abandonar sem ordem superior o posto ou serviço designado. Pena: detenção de 3 meses a 1 ano.'),
('161', 'Descumprimento de missão - Deixar de desempenhar missão confiada. Pena: detenção de 6 meses a 2 anos.'),
('162', 'Embriaguez em serviço - Embriagar-se quando em serviço ou apresentar-se embriagado. Pena: detenção de 3 meses a 1 ano.'),
('163', 'Dormir em serviço - Dormir quando em serviço de sentinela, vigia, plantão ou ronda. Pena: detenção de 3 meses a 1 ano.'),
('187', 'Violência contra superior - Praticar violência contra superior. Pena: reclusão de 3 a 9 anos.'),
('205', 'Desacato a superior - Desacatar superior ofendendo sua dignidade ou procurando deprimir sua autoridade. Pena: detenção de 1 a 2 anos.'),
('206', 'Desacato a militar - Desacatar militar no exercício da função. Pena: detenção de 6 meses a 2 anos.'),
('235', 'Peculato - Apropriar-se de dinheiro ou bem móvel público ou particular de que tem posse em razão do cargo. Pena: reclusão de 2 a 12 anos.'),
('240', 'Prevaricação - Retardar ou deixar de praticar ato de ofício indevidamente para satisfazer interesse pessoal. Pena: detenção de 6 meses a 2 anos.'),
('244', 'Condescendência criminosa - Deixar por indulgência de responsabilizar subordinado que comete infração. Pena: detenção de 6 meses a 2 anos.'),
('250', 'Violação de sigilo militar - Revelar segredo comprometendo a segurança nacional. Pena: reclusão de 2 a 8 anos.'),
('290', 'Divulgação de segredo - Divulgar sem autorização conteúdo de documento secreto ou reservado. Pena: detenção de 6 meses a 2 anos.'),
('298', 'Homicídio simples - Matar alguém. Pena: reclusão de 6 a 20 anos.'),
('299', 'Homicídio qualificado - Homicídio cometido mediante paga, motivo fútil, veneno, tortura. Pena: reclusão de 12 a 30 anos.'),
('301', 'Genocídio - Matar membros de grupo; causar lesão grave; submeter a condições de destruição; impedir nascimentos; transferência forçada de crianças. Pena: reclusão de 15 a 30 anos.'),
('303', 'Lesão corporal - Ofender a integridade corporal ou saúde de outrem. Pena: detenção de 3 meses a 1 ano.'),
('304', 'Lesão corporal grave - Se resulta incapacidade por mais de 30 dias; perigo de vida; debilidade permanente. Pena: reclusão de 1 a 5 anos.'),
('305', 'Lesão corporal gravíssima - Se resulta incapacidade permanente; enfermidade incurável; perda de membro; deformidade; aborto. Pena: reclusão de 2 a 8 anos.'),
('306', 'Rixa - Participar de rixa, salvo para separar contendores. Pena: detenção de 6 meses a 2 anos.'),
('315', 'Perigo de vida para outrem - Expor vida de outrem a perigo direto e iminente. Pena: detenção de 3 meses a 1 ano.'),
('326', 'Furto - Subtrair coisa alheia móvel para si ou outrem. Pena: reclusão de até 6 anos.'),
('328', 'Roubo - Subtrair coisa mediante grave ameaça ou violência a pessoa. Pena: reclusão de 4 a 10 anos.'),
('329', 'Extorsão - Constranger mediante violência para obter vantagem econômica indevida. Pena: reclusão de 4 a 10 anos.'),
('334', 'Apropriação indébita - Apropriar-se de coisa alheia móvel de que tem posse ou detenção. Pena: reclusão de 1 a 4 anos.'),
('338', 'Estelionato - Obter vantagem ilícita em prejuízo alheio mediante artifício ou ardil. Pena: reclusão de 1 a 5 anos.'),
('340', 'Dano - Destruir, inutilizar ou deteriorar coisa alheia. Pena: detenção de 6 meses a 3 anos.'),
('344', 'Incêndio - Causar incêndio expondo a perigo vida, integridade física ou patrimônio. Pena: reclusão de 3 a 6 anos.'),
('345', 'Explosão - Causar explosão expondo a perigo vida, integridade física ou patrimônio. Pena: reclusão de 3 a 6 anos.'),
('347', 'Inundação - Causar inundação expondo a perigo vida, integridade física ou patrimônio. Pena: reclusão de 3 a 6 anos.'),
('349', 'Desabamento ou desmoronamento - Causar desabamento expondo a perigo vida ou patrimônio. Pena: reclusão de 1 a 4 anos.'),
('368', 'Tráfico de entorpecente - Importar, exportar, produzir, fabricar, vender, ter em depósito, transportar drogas. Pena: reclusão de 3 a 15 anos.'),
('380', 'Falsificação de documento - Falsificar no todo ou em parte documento público ou alterar documento verdadeiro. Pena: reclusão de 2 a 6 anos.'),
('390', 'Calúnia - Caluniar alguém imputando-lhe falsamente fato definido como crime. Pena: detenção de 6 meses a 2 anos.'),
('391', 'Difamação - Difamar alguém imputando-lhe fato ofensivo à reputação. Pena: detenção de 3 meses a 1 ano.'),
('392', 'Injúria - Injuriar alguém ofendendo sua dignidade ou decoro. Pena: detenção de 1 a 6 meses.'),
('409', 'Vigência - Este Código entrou em vigor no dia 1º de janeiro de 1970.'),
('410', 'Revogação - Ficam revogados o Código Penal Militar anterior e demais disposições em contrário.');